version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=credit-store
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks: 
      - default
    ports:
      - "16001:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
